/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as DashboardStatsRouteImport } from './routes/dashboard/stats'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appUsersRouteImport } from './routes/(app)/users'
import { Route as appSpaRouteImport } from './routes/(app)/spa'
import { Route as appRoomsRouteImport } from './routes/(app)/rooms'
import { Route as appRestaurantRouteImport } from './routes/(app)/restaurant'
import { Route as appContactRouteImport } from './routes/(app)/contact'
import { Route as appBookingsRouteImport } from './routes/(app)/bookings'
import { Route as appAboutRouteImport } from './routes/(app)/about'
import { Route as appprivateRouteRouteImport } from './routes/(app)/(private)/route'
import { Route as DashboardRoomsIndexRouteImport } from './routes/dashboard/rooms/index'
import { Route as DashboardRoomTypesIndexRouteImport } from './routes/dashboard/room-types/index'
import { Route as DashboardGuestsIndexRouteImport } from './routes/dashboard/guests/index'
import { Route as DashboardBedsIndexRouteImport } from './routes/dashboard/beds/index'
import { Route as DashboardAmenitiesIndexRouteImport } from './routes/dashboard/amenities/index'
import { Route as DashboardRoomsIdRouteImport } from './routes/dashboard/rooms.$id'
import { Route as DashboardGuestsIdRouteImport } from './routes/dashboard/guests/$id'
import { Route as appRoomsRoomTypeIdRouteImport } from './routes/(app)/rooms.$roomTypeId'
import { Route as appprivateProfileRouteImport } from './routes/(app)/(private)/profile'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appUsersRoute = appUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appRouteRoute,
} as any)
const appSpaRoute = appSpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => appRouteRoute,
} as any)
const appRoomsRoute = appRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => appRouteRoute,
} as any)
const appRestaurantRoute = appRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => appRouteRoute,
} as any)
const appContactRoute = appContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => appRouteRoute,
} as any)
const appBookingsRoute = appBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const appprivateRouteRoute = appprivateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => appRouteRoute,
} as any)
const DashboardRoomsIndexRoute = DashboardRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRoomTypesIndexRoute = DashboardRoomTypesIndexRouteImport.update({
  id: '/room-types/',
  path: '/room-types/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuestsIndexRoute = DashboardGuestsIndexRouteImport.update({
  id: '/guests/',
  path: '/guests/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBedsIndexRoute = DashboardBedsIndexRouteImport.update({
  id: '/beds/',
  path: '/beds/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAmenitiesIndexRoute = DashboardAmenitiesIndexRouteImport.update({
  id: '/amenities/',
  path: '/amenities/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRoomsIdRoute = DashboardRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuestsIdRoute = DashboardGuestsIdRouteImport.update({
  id: '/guests/$id',
  path: '/guests/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const appRoomsRoomTypeIdRoute = appRoomsRoomTypeIdRouteImport.update({
  id: '/$roomTypeId',
  path: '/$roomTypeId',
  getParentRoute: () => appRoomsRoute,
} as any)
const appprivateProfileRoute = appprivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appprivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof appAboutRoute
  '/bookings': typeof appBookingsRoute
  '/contact': typeof appContactRoute
  '/restaurant': typeof appRestaurantRoute
  '/rooms': typeof appRoomsRouteWithChildren
  '/spa': typeof appSpaRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/': typeof appIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile': typeof appprivateProfileRoute
  '/rooms/$roomTypeId': typeof appRoomsRoomTypeIdRoute
  '/dashboard/guests/$id': typeof DashboardGuestsIdRoute
  '/dashboard/rooms/$id': typeof DashboardRoomsIdRoute
  '/dashboard/amenities/': typeof DashboardAmenitiesIndexRoute
  '/dashboard/beds/': typeof DashboardBedsIndexRoute
  '/dashboard/guests/': typeof DashboardGuestsIndexRoute
  '/dashboard/room-types/': typeof DashboardRoomTypesIndexRoute
  '/dashboard/rooms/': typeof DashboardRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/bookings': typeof appBookingsRoute
  '/contact': typeof appContactRoute
  '/restaurant': typeof appRestaurantRoute
  '/rooms': typeof appRoomsRouteWithChildren
  '/spa': typeof appSpaRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/': typeof appIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof appprivateProfileRoute
  '/rooms/$roomTypeId': typeof appRoomsRoomTypeIdRoute
  '/dashboard/guests/$id': typeof DashboardGuestsIdRoute
  '/dashboard/rooms/$id': typeof DashboardRoomsIdRoute
  '/dashboard/amenities': typeof DashboardAmenitiesIndexRoute
  '/dashboard/beds': typeof DashboardBedsIndexRoute
  '/dashboard/guests': typeof DashboardGuestsIndexRoute
  '/dashboard/room-types': typeof DashboardRoomTypesIndexRoute
  '/dashboard/rooms': typeof DashboardRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(app)/(private)': typeof appprivateRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(app)/bookings': typeof appBookingsRoute
  '/(app)/contact': typeof appContactRoute
  '/(app)/restaurant': typeof appRestaurantRoute
  '/(app)/rooms': typeof appRoomsRouteWithChildren
  '/(app)/spa': typeof appSpaRoute
  '/(app)/users': typeof appUsersRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/(app)/': typeof appIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(app)/(private)/profile': typeof appprivateProfileRoute
  '/(app)/rooms/$roomTypeId': typeof appRoomsRoomTypeIdRoute
  '/dashboard/guests/$id': typeof DashboardGuestsIdRoute
  '/dashboard/rooms/$id': typeof DashboardRoomsIdRoute
  '/dashboard/amenities/': typeof DashboardAmenitiesIndexRoute
  '/dashboard/beds/': typeof DashboardBedsIndexRoute
  '/dashboard/guests/': typeof DashboardGuestsIndexRoute
  '/dashboard/room-types/': typeof DashboardRoomTypesIndexRoute
  '/dashboard/rooms/': typeof DashboardRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/restaurant'
    | '/rooms'
    | '/spa'
    | '/users'
    | '/login'
    | '/signup'
    | '/dashboard/bookings'
    | '/dashboard/reviews'
    | '/dashboard/staff'
    | '/dashboard/stats'
    | '/'
    | '/dashboard/'
    | '/profile'
    | '/rooms/$roomTypeId'
    | '/dashboard/guests/$id'
    | '/dashboard/rooms/$id'
    | '/dashboard/amenities/'
    | '/dashboard/beds/'
    | '/dashboard/guests/'
    | '/dashboard/room-types/'
    | '/dashboard/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/bookings'
    | '/contact'
    | '/restaurant'
    | '/rooms'
    | '/spa'
    | '/users'
    | '/login'
    | '/signup'
    | '/dashboard/bookings'
    | '/dashboard/reviews'
    | '/dashboard/staff'
    | '/dashboard/stats'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/rooms/$roomTypeId'
    | '/dashboard/guests/$id'
    | '/dashboard/rooms/$id'
    | '/dashboard/amenities'
    | '/dashboard/beds'
    | '/dashboard/guests'
    | '/dashboard/room-types'
    | '/dashboard/rooms'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/dashboard'
    | '/(app)/(private)'
    | '/(app)/about'
    | '/(app)/bookings'
    | '/(app)/contact'
    | '/(app)/restaurant'
    | '/(app)/rooms'
    | '/(app)/spa'
    | '/(app)/users'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/dashboard/bookings'
    | '/dashboard/reviews'
    | '/dashboard/staff'
    | '/dashboard/stats'
    | '/(app)/'
    | '/dashboard/'
    | '/(app)/(private)/profile'
    | '/(app)/rooms/$roomTypeId'
    | '/dashboard/guests/$id'
    | '/dashboard/rooms/$id'
    | '/dashboard/amenities/'
    | '/dashboard/beds/'
    | '/dashboard/guests/'
    | '/dashboard/room-types/'
    | '/dashboard/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/users': {
      id: '/(app)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/spa': {
      id: '/(app)/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof appSpaRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/rooms': {
      id: '/(app)/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof appRoomsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/restaurant': {
      id: '/(app)/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof appRestaurantRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contact': {
      id: '/(app)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof appContactRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/bookings': {
      id: '/(app)/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof appBookingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(private)': {
      id: '/(app)/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appprivateRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/dashboard/rooms/': {
      id: '/dashboard/rooms/'
      path: '/rooms'
      fullPath: '/dashboard/rooms/'
      preLoaderRoute: typeof DashboardRoomsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/room-types/': {
      id: '/dashboard/room-types/'
      path: '/room-types'
      fullPath: '/dashboard/room-types/'
      preLoaderRoute: typeof DashboardRoomTypesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guests/': {
      id: '/dashboard/guests/'
      path: '/guests'
      fullPath: '/dashboard/guests/'
      preLoaderRoute: typeof DashboardGuestsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/beds/': {
      id: '/dashboard/beds/'
      path: '/beds'
      fullPath: '/dashboard/beds/'
      preLoaderRoute: typeof DashboardBedsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/amenities/': {
      id: '/dashboard/amenities/'
      path: '/amenities'
      fullPath: '/dashboard/amenities/'
      preLoaderRoute: typeof DashboardAmenitiesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rooms/$id': {
      id: '/dashboard/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/dashboard/rooms/$id'
      preLoaderRoute: typeof DashboardRoomsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guests/$id': {
      id: '/dashboard/guests/$id'
      path: '/guests/$id'
      fullPath: '/dashboard/guests/$id'
      preLoaderRoute: typeof DashboardGuestsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(app)/rooms/$roomTypeId': {
      id: '/(app)/rooms/$roomTypeId'
      path: '/$roomTypeId'
      fullPath: '/rooms/$roomTypeId'
      preLoaderRoute: typeof appRoomsRoomTypeIdRouteImport
      parentRoute: typeof appRoomsRoute
    }
    '/(app)/(private)/profile': {
      id: '/(app)/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appprivateProfileRouteImport
      parentRoute: typeof appprivateRouteRoute
    }
  }
}

interface appprivateRouteRouteChildren {
  appprivateProfileRoute: typeof appprivateProfileRoute
}

const appprivateRouteRouteChildren: appprivateRouteRouteChildren = {
  appprivateProfileRoute: appprivateProfileRoute,
}

const appprivateRouteRouteWithChildren = appprivateRouteRoute._addFileChildren(
  appprivateRouteRouteChildren,
)

interface appRoomsRouteChildren {
  appRoomsRoomTypeIdRoute: typeof appRoomsRoomTypeIdRoute
}

const appRoomsRouteChildren: appRoomsRouteChildren = {
  appRoomsRoomTypeIdRoute: appRoomsRoomTypeIdRoute,
}

const appRoomsRouteWithChildren = appRoomsRoute._addFileChildren(
  appRoomsRouteChildren,
)

interface appRouteRouteChildren {
  appprivateRouteRoute: typeof appprivateRouteRouteWithChildren
  appAboutRoute: typeof appAboutRoute
  appBookingsRoute: typeof appBookingsRoute
  appContactRoute: typeof appContactRoute
  appRestaurantRoute: typeof appRestaurantRoute
  appRoomsRoute: typeof appRoomsRouteWithChildren
  appSpaRoute: typeof appSpaRoute
  appUsersRoute: typeof appUsersRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appprivateRouteRoute: appprivateRouteRouteWithChildren,
  appAboutRoute: appAboutRoute,
  appBookingsRoute: appBookingsRoute,
  appContactRoute: appContactRoute,
  appRestaurantRoute: appRestaurantRoute,
  appRoomsRoute: appRoomsRouteWithChildren,
  appSpaRoute: appSpaRoute,
  appUsersRoute: appUsersRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuestsIdRoute: typeof DashboardGuestsIdRoute
  DashboardRoomsIdRoute: typeof DashboardRoomsIdRoute
  DashboardAmenitiesIndexRoute: typeof DashboardAmenitiesIndexRoute
  DashboardBedsIndexRoute: typeof DashboardBedsIndexRoute
  DashboardGuestsIndexRoute: typeof DashboardGuestsIndexRoute
  DashboardRoomTypesIndexRoute: typeof DashboardRoomTypesIndexRoute
  DashboardRoomsIndexRoute: typeof DashboardRoomsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuestsIdRoute: DashboardGuestsIdRoute,
  DashboardRoomsIdRoute: DashboardRoomsIdRoute,
  DashboardAmenitiesIndexRoute: DashboardAmenitiesIndexRoute,
  DashboardBedsIndexRoute: DashboardBedsIndexRoute,
  DashboardGuestsIndexRoute: DashboardGuestsIndexRoute,
  DashboardRoomTypesIndexRoute: DashboardRoomTypesIndexRoute,
  DashboardRoomsIndexRoute: DashboardRoomsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
